// <auto-generated />
namespace PizzaShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class CatalogAnotations_ProductWeightToDouble : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CatalogAnotations_ProductWeightToDouble));
        
        string IMigrationMetadata.Id
        {
            get { return "201212061722111_CatalogAnotations_ProductWeightToDouble"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
