// <auto-generated />
namespace PizzaShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class DescriptionProductImageProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(DescriptionProductImageProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "201212051308024_DescriptionProductImageProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
