// <auto-generated />
namespace PizzaShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Route_OrdersTotal : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Route_OrdersTotal));
        
        string IMigrationMetadata.Id
        {
            get { return "201305152020504_Route_OrdersTotal"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
