// <auto-generated />
namespace PizzaShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Car_priceForLiter : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Car_priceForLiter));
        
        string IMigrationMetadata.Id
        {
            get { return "201305170540398_Car_priceForLiter"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
