// <auto-generated />
namespace PizzaShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Order2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order2));
        
        string IMigrationMetadata.Id
        {
            get { return "201302051350341_Order2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
