// <auto-generated />
namespace PizzaShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Route_OrdersCosts : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Route_OrdersCosts));
        
        string IMigrationMetadata.Id
        {
            get { return "201305151926244_Route_OrdersCosts"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
