// <auto-generated />
namespace PizzaShop.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Order_with_anotations : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Order_with_anotations));
        
        string IMigrationMetadata.Id
        {
            get { return "201302121049346_Order_with_anotations"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
